name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests & Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 black isort mypy pytest

      - name: Run Linting (Flake8, Black, Isort)
        run: |
          source venv/bin/activate
          flake8 api/ --max-line-length=88
          black --check api/
          isort --check-only api/

      - name: Run Type Checking (Mypy)
        run: |
          source venv/bin/activate
          mypy api/

      - name: Run Pytest
        run: |
          source venv/bin/activate
          pytest --maxfail=5 --disable-warnings

      - name: Start FastAPI and Validate API
        run: |
          source venv/bin/activate
          uvicorn main:app --host 127.0.0.1 --port 8000 --reload &  # Start FastAPI in the background
          sleep 5  # Wait for server to start
          curl -f http://127.0.0.1:8000/healthcheck  # Ensure FastAPI is running

